# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x07\x65xample\"9\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x10\n\x08zip_code\x18\x03 \x01(\t\"\xdb\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\x05phone\x18\x04 \x01(\tH\x00\x88\x01\x01\x12!\n\x07\x61\x64\x64ress\x18\x05 \x01(\x0b\x32\x10.example.Address\x12\x0f\n\x07hobbies\x18\x06 \x03(\t\x12\x11\n\tis_active\x18\x07 \x01(\x08\x12\x13\n\x06salary\x18\x08 \x01(\x01H\x01\x88\x01\x01\x12\"\n\x08\x63ontacts\x18\t \x03(\x0b\x32\x10.example.ContactB\x08\n\x06_phoneB\t\n\x07_salary\"2\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDRESS']._serialized_start=23
  _globals['_ADDRESS']._serialized_end=80
  _globals['_PERSON']._serialized_start=83
  _globals['_PERSON']._serialized_end=302
  _globals['_CONTACT']._serialized_start=304
  _globals['_CONTACT']._serialized_end=354
# @@protoc_insertion_point(module_scope)
